server:
    host: 0.0.0.0
    port: 8077

    cors:
        enabled: true
        allow_origins: 
            - "http://127.0.0.1:8077"
            - "http://192.168.1.87:8077"
            - "http://192.168.1.50:8077"
            - "http://192.168.1.83:8077"
            - "http://localhost:8077"
        allow_methods:
            - GET
            - POST
            - OPTIONS
            - PUT
            - DELETE
            - PATCH
        credentials: true
data:
    data_dir: ./data
    static_dir: ./client